[versions]
composeBom = "2023.10.01"
lifecycle = "2.6.2"
navigation = "2.7.6"
moshi = "1.15.0"
hilt = "2.50"
retrofit = "2.9.0"
coroutines = "1.7.3"
okHttp = "4.12.0"
composeActivity = "1.9.0-alpha01"
core = "1.13.0-alpha02"
appcompat = "1.7.0-alpha03"
material = "1.11.0"
datastore = "1.1.0-beta01"
paging = "3.2.1"
coil = "2.5.0"
hiltNavigation = "1.1.0"
crashlytics = "18.6.0"
analytics = "21.5.0"
junit = "4.13.2"
espresso = "3.5.1"
extJunit = "1.1.5"
constraintLayout = "1.1.0-alpha11"
iconsExtended = "1.6.0-beta03"
material3 = "1.2.0-beta01"
messaging = "23.4.0"
mockWebServer = "4.12.0"
truth = "1.2.0"

[libraries]
coil = { group = "io.coil-kt", name = "coil-compose", version.ref = "coil" }